import Head from 'next/head';
import styles from '../styles/Teams.module.css';
import { Team } from '../components/Team';

export const URL = 'https://www.balldontlie.io/api/v1';
export const teamsEndpoint = '/teams';

export default function Teams({teams}) {
    
    return (
        <>
            <Head>
                <title>💻 Teams 🏀</title>
                <meta name="description" content="Generated by create next app to test NextJS" />
            </Head>
            
            <div className={styles.container}>
                <ul>
                    {teams.map(team => <Team team={team}/>)}
                </ul>
            </div>
        </>
    )
}

export async function getServerSideProps(context) {
    const data = await fetch(`${URL}${teamsEndpoint}`);
    const dataJSON = await data.json();
    const teams = dataJSON.data;

    return {
        props: {
            teams
        }
    }
}