import Head from 'next/head'
import Header from '../components/Header';
import { teamLogos } from '../components/Team';

import styles from '../styles/Home.module.css'

export default function Home() {
    const logos = [];

    for (let i = 0; i < 40; i++) {
      for (let j = 0; j < teamLogos.length; j++) {
        logos.push(teamLogos[j]);
      }
    }

    return (
        <>
          <Head>
          <title>💻 Home 🏀</title>
          <meta name="description" content="Generated by create next app to test NextJS" />
          </Head>
    
          <Header />
          <div className={styles.container}>
              <h1>WELCOME TO <span className={styles.nba}>NBA</span></h1>
              <main className={styles.main}>
                <div className={styles.firstRow}>{logos.map(logo => <img key={logos.indexOf(logo)} src={logo}/>)}</div>
                <div className={styles.secondRow}>{logos.map(logo => <img key={logos.indexOf(logo)} src={logo}/>)}</div>
            </main>
          </div>
        </>
      )
}