import Head from 'next/head'
import Link from 'next/link';
import styles from '../styles/Index.module.css'

export const URL = 'https://www.balldontlie.io/api/v1';

export default function index() {
  return (
    <>
      <Head>
        <title>💻 NBA Data 🏀</title>
        <meta name="description" content="Generated by create next app to test NextJS" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@400;600&family=Roboto:wght@300;400;700;900&display=swap" rel="stylesheet"/> 
      </Head>

      <div className={styles.container}>
        <Link href="/home">
          <div className={styles.homeContainer}>Home</div>
        </Link>
        <Link href="/games">
          <div className={styles.gamesContainer}>Games</div>
        </Link>
        <Link href='/teams'>
          <div className={styles.teamsContainer}>Teams</div>
        </Link>
      </div>
    </>
  )
}